spring:
  data:
    mongodb:
      uri: ${env.MONGO_URI}
  task:
    scheduling:
      pool:
        size: 10

ontology:
  uri: ${env.ONTOLOGY_URI}

transitions:
  file: ${env.TRANSITIONS_FILE}

states:
  updateDelay: ${env.STATES_UPDATE_DELAY}