name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_MONGO_URI: ${{ secrets.MONGO_URI }}
          envkey_ONTOLOGY_URI: ${{ secrets.ONTOLOGY_URI }}
          envkey_TRANSITIONS_FILE: ${{ secrets.TRANSITIONS_FILE }}
          envkey_TWINS_UPDATE_DELAY: ${{ secrets.TWINS_UPDATE_DELAY }}
          directory: "src/main/resources"
          file_name: .env

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: smartglass-backend.jar
          path: target

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@master

      - name: Download tested artifact
        uses: actions/download-artifact@master
        with:
          name: smartglass-backend.jar
          path: target

      - name: Build docker image and push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: adrianliz/smartglass-backend
          tag_with_ref: true