name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Change mvnw permissions
        run: chmod +x ./mvnw

      - name: Run the tests
        run: make test

  deploy:
    name: Deploy to docker hub
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v1
      - name: Change mvnw permissions
        run: chmod +x ./mvnw

      - name: Build
        run: make build

      - name: Push to docker hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: adrianliz/smartglass-backend
          tag_with_ref: true